### ISSUE TITLE
baldor makes the package fails

### ISSUE THREAD

**Issue by hassan-tht** [ros-planning/moveit_calibration#133]
Hi

I got the following error when I try to do the hand-eye calibration:

```
[ERROR] [1681225883.511651768]: Failed to load python module: handeye.calibrator
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/handeye/__init__.py", line 2, in <module>
    from .calibrator import HandEyeCalibrator, Setup
  File "/opt/ros/noetic/lib/python3/dist-packages/handeye/calibrator.py", line 5, in <module>
    import baldor as br
  File "/opt/ros/noetic/lib/python3/dist-packages/baldor/__init__.py", line 13, in <module>
    _MAX_FLOAT = np.maximum_sctype(np.float)
  File "/home/tht/.local/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
```
I'm using `Noetic` and my `Numpy` version is `1.24` which explains the error as `np.float` has been depreciated. A quick fix for me was to change the corresponding lines in `opt/ros/noetic/lib/python3/dist-packages/baldor/__init__.py` that have the `np.float` to just `float`

**Comment by bmegli** [comment]
Looks like it was fixed in baldor code
- https://github.com/crigroup/baldor/pull/7

Looking at commits package with the fixes has not been released yet
- https://github.com/crigroup/baldor/commits/master

Other ad-hoc fix options are probably:
- build baldor from source
- downgrade numpy to pre 1.24
- and one mentioned by @hassan-tht above

**Comment by hassan-tht** [comment]
Thanks for the note regarding development/production machines. Downgrading is of course a valid option, but we have other related software stack that might complain if we downgrade
