### ISSUE TITLE
[Noetic] Package moveit_calibration_plugins fails to build on all platforms

### ISSUE THREAD

**Issue by sloretz** [ros-planning/moveit_calibration#135]
Hello @JStech,

It looks like the package `moveit_calibration_plugins` is not building on any platform on the ROS Noetic buildfarm.

• [Ubuntu Focal amd64](https://build.ros.org/view/Nbin_uF64/job/Nbin_uF64__moveit_calibration_plugins__ubuntu_focal_amd64__binary/)
• [Ubuntu Focal armhf](https://build.ros.org/job/Nbin_ufhf_uFhf__moveit_calibration_plugins__ubuntu_focal_armhf__binary/)
• [Ubuntu Focal armv8](https://build.ros.org/job/Nbin_ufv8_uFv8__moveit_calibration_plugins__ubuntu_focal_arm64__binary/)

I am removing the release of this package from Noetic so the buildfarm doesn't keep trying to build it. Please make another release with `bloom-release` once the build failure is fixed.

**Comment by JStech** [comment]
I am not very involved with this project any more. Maybe @Abishalini can help?

**Comment by sloretz** [comment]
Looks like it's still failing to build on all platforms.

```
23:01:35 Traceback (most recent call last):
23:01:35   File "/usr/lib/python3/dist-packages/apt/cache.py", line 299, in __getitem__
23:01:35     rawpkg = self._cache[key]
23:01:35 KeyError: 'ros-noetic-moveit-calibration-plugins'
23:01:35 
23:01:35 During handling of the above exception, another exception occurred:
23:01:35 
23:01:35 Traceback (most recent call last):
23:01:35   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 21, in <module>
23:01:35     run_module('ros_buildfarm.scripts.release.create_binarydeb_task_generator', run_name='__main__')
23:01:35   File "/usr/lib/python3.8/runpy.py", line 210, in run_module
23:01:35     return _run_code(code, {}, init_globals, run_name, mod_spec)
23:01:35   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
23:01:35     exec(code, run_globals)
23:01:35   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 214, in <module>
23:01:35     sys.exit(main())
23:01:35   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 89, in main
23:01:35     debian_pkg_versions = get_binary_package_versions(
23:01:35   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 175, in get_binary_package_versions
23:01:35     pkg = apt_cache[debian_pkg_name]
23:01:35   File "/usr/lib/python3/dist-packages/apt/cache.py", line 301, in __getitem__
23:01:35     raise KeyError('The cache has no package named %r' % key)
23:01:35 KeyError: "The cache has no package named 'ros-noetic-moveit-calibration-plugins'"
```

**Comment by sloretz** [comment]
Ah, moveit_calibration_gui is probably failing because moveit_calibration_plugins was removed in https://github.com/ros/rosdistro/pull/37323/files

I should have removed both of them in that PR. Either way, fixing moveit_calibration_plugins and re-running bloom should resolve the issue.
